### ISSUE TITLE
Luciex Logo

### ISSUE THREAD

**Issue by shadowtime2000** [lucialand/luciex#1]
Before we create a Luciex documentation site, I think we should create a logo or icon for it. I also think we should base it off of the Lucia logo. Maybe the Lucia logo but instead of purple you have blue?

**Comment by shadowtime2000** [comment]
@aidenybai Thoughts?

**Comment by aidenybai** [comment]
![luciex](https://user-images.githubusercontent.com/38025074/98745735-f2ae1d00-2368-11eb-95b8-728605632f6b.png)

**Comment by shadowtime2000** [comment]
@aidenybai I like it! Mind if I use it for the branding of Luciex?

**Comment by aidenybai** [comment]
Sure, I wasn't really able to integrate the x wit the original logo, so i settled on that

**Comment by shadowtime2000** [comment]
@aidenybai Could you create a banner for it kind of like the banner for Lucia?
